//! Deterministic, narrowly scoped Gmsh `.geo` generation.

use super::MeshingError;
use crate::MeshDimension;

#[derive(Clone, Debug, PartialEq)]
pub struct GmshGeoDocument {
    dimension: MeshDimension,
    source: String,
}

impl GmshGeoDocument {
    pub(crate) fn from_source(dimension: MeshDimension, source: String) -> Self {
        Self { dimension, source }
    }

    /// Builds an XY-plane rectangle with stable point, curve, loop, and surface tags.
    /// Curve tags are bottom=1, right=2, top=3, left=4; the fluid surface is 1.
    pub fn rectangle(
        width: f64,
        height: f64,
        boundary_groups: impl IntoIterator<Item = (impl AsRef<str>, Vec<usize>)>,
        fluid_name: impl AsRef<str>,
    ) -> Result<Self, MeshingError> {
        if !(width.is_finite() && width > 0.0 && height.is_finite() && height > 0.0) {
            return Err(MeshingError::InvalidGeometry {
                message: "rectangle width and height must be finite and positive".into(),
            });
        }
        validate_name(fluid_name.as_ref())?;
        let mut groups = boundary_groups
            .into_iter()
            .map(|(name, curves)| (name.as_ref().to_owned(), curves))
            .collect::<Vec<_>>();
        groups.sort_by(|left, right| left.0.cmp(&right.0));
        for (name, curves) in &groups {
            validate_name(name)?;
            if curves.is_empty() || curves.iter().any(|curve| !(1..=4).contains(curve)) {
                return Err(MeshingError::InvalidGeometry {
                    message: format!(
                        "rectangle physical curve group {name:?} references invalid curves"
                    ),
                });
            }
        }
        let mut source = String::new();
        source.push_str("// Generated by FLURSYS; deterministic Gmsh 4 ASCII input.\n");
        source.push_str(&format!(
            "Point(1) = {{0, 0, 0}};\nPoint(2) = {{{width:.17}, 0, 0}};\n"
        ));
        source.push_str(&format!(
            "Point(3) = {{{width:.17}, {height:.17}, 0}};\nPoint(4) = {{0, {height:.17}, 0}};\n"
        ));
        source.push_str(
            "Line(1) = {1, 2};\nLine(2) = {2, 3};\nLine(3) = {3, 4};\nLine(4) = {4, 1};\n",
        );
        source.push_str("Curve Loop(1) = {1, 2, 3, 4};\nPlane Surface(1) = {1};\n");
        for (name, curves) in groups {
            let curves = curves
                .iter()
                .map(usize::to_string)
                .collect::<Vec<_>>()
                .join(", ");
            source.push_str(&format!("Physical Curve(\"{name}\") = {{{curves}}};\n"));
        }
        source.push_str(&format!(
            "Physical Surface(\"{}\") = {{1}};\n",
            fluid_name.as_ref()
        ));
        Ok(Self {
            dimension: MeshDimension::TwoD,
            source,
        })
    }

    /// Builds a rectangular channel with a circular hole. Curve tags are
    /// bottom=1, right=2, top=3, left=4, then the cylinder arcs=5..8.
    pub fn rectangle_with_circle(
        width: f64,
        height: f64,
        center_x: f64,
        center_y: f64,
        radius: f64,
    ) -> Result<Self, MeshingError> {
        if !(width.is_finite()
            && width > 0.0
            && height.is_finite()
            && height > 0.0
            && center_x.is_finite()
            && center_y.is_finite()
            && radius.is_finite()
            && radius > 0.0
            && center_x - radius > 0.0
            && center_x + radius < width
            && center_y - radius > 0.0
            && center_y + radius < height)
        {
            return Err(MeshingError::InvalidGeometry {
                message: "circle must be finite, positive, and strictly inside the rectangle"
                    .into(),
            });
        }
        let east_x = center_x + radius;
        let north_y = center_y + radius;
        let west_x = center_x - radius;
        let south_y = center_y - radius;
        let mut source =
            String::from("// Generated by FLURSYS; deterministic Gmsh 4 ASCII input.\n");
        source.push_str(&format!(
            "Point(1) = {{0, 0, 0}};\nPoint(2) = {{{width:.17}, 0, 0}};\n"
        ));
        source.push_str(&format!(
            "Point(3) = {{{width:.17}, {height:.17}, 0}};\nPoint(4) = {{0, {height:.17}, 0}};\n"
        ));
        source.push_str(&format!(
            "Point(5) = {{{center_x:.17}, {center_y:.17}, 0}};\nPoint(6) = {{{east_x:.17}, {center_y:.17}, 0}};\n"
        ));
        source.push_str(&format!(
            "Point(7) = {{{center_x:.17}, {north_y:.17}, 0}};\nPoint(8) = {{{west_x:.17}, {center_y:.17}, 0}};\nPoint(9) = {{{center_x:.17}, {south_y:.17}, 0}};\n"
        ));
        source.push_str(
            "Line(1) = {1, 2};\nLine(2) = {2, 3};\nLine(3) = {3, 4};\nLine(4) = {4, 1};\n",
        );
        source.push_str("Circle(5) = {6, 5, 7};\nCircle(6) = {7, 5, 8};\nCircle(7) = {8, 5, 9};\nCircle(8) = {9, 5, 6};\n");
        source.push_str("Curve Loop(1) = {1, 2, 3, 4};\nCurve Loop(2) = {-8, -7, -6, -5};\nPlane Surface(1) = {1, 2};\n");
        source.push_str("Physical Curve(\"inlet\") = {4};\nPhysical Curve(\"outlet\") = {2};\nPhysical Curve(\"walls\") = {1, 3};\nPhysical Curve(\"cylinder\") = {5, 6, 7, 8};\nPhysical Surface(\"fluid\") = {1};\n");
        Ok(Self {
            dimension: MeshDimension::TwoD,
            source,
        })
    }

    /// Builds a rectangular OpenCASCADE volume with stable volume tag 1.
    /// The six generated exterior surface tags are explicitly grouped by the
    /// caller; this keeps physical names independent of final mesh-face IDs.
    pub fn rectangular_box(
        length: f64,
        width: f64,
        height: f64,
        boundary_groups: impl IntoIterator<Item = (impl AsRef<str>, Vec<usize>)>,
        fluid_name: impl AsRef<str>,
    ) -> Result<Self, MeshingError> {
        if !(length.is_finite()
            && length > 0.0
            && width.is_finite()
            && width > 0.0
            && height.is_finite()
            && height > 0.0)
        {
            return Err(MeshingError::InvalidGeometry {
                message: "box dimensions must be finite and positive".into(),
            });
        }
        validate_name(fluid_name.as_ref())?;
        let mut groups = boundary_groups
            .into_iter()
            .map(|(name, surfaces)| (name.as_ref().to_owned(), surfaces))
            .collect::<Vec<_>>();
        groups.sort_by(|left, right| left.0.cmp(&right.0));
        for (name, surfaces) in &groups {
            validate_name(name)?;
            if surfaces.is_empty() || surfaces.iter().any(|surface| !(1..=6).contains(surface)) {
                return Err(MeshingError::InvalidGeometry {
                    message: format!(
                        "box physical surface group {name:?} references invalid surfaces"
                    ),
                });
            }
        }
        let mut source =
            String::from("// Generated by FLURSYS; deterministic Gmsh 4 ASCII input.\n");
        source.push_str("SetFactory(\"OpenCASCADE\");\n");
        source.push_str(&format!(
            "Box(1) = {{0, 0, 0, {length:.17}, {width:.17}, {height:.17}}};\n"
        ));
        for (name, surfaces) in groups {
            let surfaces = surfaces
                .iter()
                .map(usize::to_string)
                .collect::<Vec<_>>()
                .join(", ");
            source.push_str(&format!("Physical Surface(\"{name}\") = {{{surfaces}}};\n"));
        }
        source.push_str(&format!(
            "Physical Volume(\"{}\") = {{1}};\n",
            fluid_name.as_ref()
        ));
        Ok(Self {
            dimension: MeshDimension::ThreeD,
            source,
        })
    }

    pub fn dimension(&self) -> MeshDimension {
        self.dimension
    }

    pub fn to_geo_string(&self) -> Result<String, MeshingError> {
        Ok(self.source.clone())
    }
}

fn validate_name(name: &str) -> Result<(), MeshingError> {
    if name.is_empty()
        || name
            .chars()
            .any(|character| character == '"' || character.is_control())
    {
        return Err(MeshingError::InvalidPhysicalName {
            name: name.to_owned(),
        });
    }
    Ok(())
}
