//! Deterministic conversion from stable geometry topology to Gmsh `.geo` input.

use super::GmshGeoDocument;
use crate::{
    BodyId, EdgeGeometry, EdgeId, FaceId, GeometryBodyRepresentation, GeometryError,
    GeometryFaceRepresentation, GeometryTopology, MeshDimension, VertexId,
};
use std::collections::BTreeMap;

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct GeometryToGmshMap {
    vertex_tags: BTreeMap<VertexId, usize>,
    edge_tags: BTreeMap<EdgeId, usize>,
    face_tags: BTreeMap<FaceId, usize>,
    body_tags: BTreeMap<BodyId, usize>,
}

impl GeometryToGmshMap {
    pub fn vertex_tag(&self, id: VertexId) -> Option<usize> {
        self.vertex_tags.get(&id).copied()
    }

    pub fn edge_tag(&self, id: EdgeId) -> Option<usize> {
        self.edge_tags.get(&id).copied()
    }

    pub fn face_tag(&self, id: FaceId) -> Option<usize> {
        self.face_tags.get(&id).copied()
    }

    pub fn body_tag(&self, id: BodyId) -> Option<usize> {
        self.body_tags.get(&id).copied()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct GeometryGmshExport {
    pub document: GmshGeoDocument,
    pub map: GeometryToGmshMap,
}

/// Exports stable topology with fresh, deterministic, backend-only Gmsh tags.
pub struct GmshGeometryExporter;

impl GmshGeometryExporter {
    pub fn planar(
        geometry: &GeometryTopology,
        face: FaceId,
        boundary_groups: impl IntoIterator<Item = (impl AsRef<str>, Vec<EdgeId>)>,
        fluid_name: impl AsRef<str>,
    ) -> Result<GeometryGmshExport, GeometryError> {
        let face_entity = geometry
            .face(face)
            .ok_or_else(|| missing("face", face.get()))?;
        let GeometryFaceRepresentation::Planar {
            outer_loop,
            inner_loops,
        } = &face_entity.representation
        else {
            return Err(GeometryError::InvalidPrimitive {
                message: "Gmsh planar export requires a planar face".into(),
            });
        };
        validate_name(fluid_name.as_ref())?;
        let mut groups = boundary_groups
            .into_iter()
            .map(|(name, edges)| (name.as_ref().to_owned(), edges))
            .collect::<Vec<_>>();
        groups.sort_by(|left, right| left.0.cmp(&right.0));
        for (name, edges) in &groups {
            validate_name(name)?;
            if edges.is_empty() {
                return Err(GeometryError::InvalidPrimitive {
                    message: format!("physical group {name:?} has no edges"),
                });
            }
            for &edge in edges {
                if geometry.edge(edge).is_none() {
                    return Err(missing("edge", edge.get()));
                }
            }
        }

        let mut map = GeometryToGmshMap::default();
        for (index, vertex) in geometry.vertices().enumerate() {
            map.vertex_tags.insert(vertex.id, 1000 + index);
        }
        for (index, edge) in geometry.edges().enumerate() {
            map.edge_tags.insert(edge.id, 2000 + index);
        }
        map.face_tags.insert(face, 3000);

        let mut source = String::from("// Generated by FLURSYS stable geometry exporter.\n");
        for vertex in geometry.vertices() {
            let tag = map.vertex_tag(vertex.id).expect("mapped vertex");
            source.push_str(&format!(
                "Point({tag}) = {{{:.17}, {:.17}, {:.17}}};\n",
                vertex.position.x, vertex.position.y, vertex.position.z
            ));
        }
        for edge in geometry.edges() {
            let tag = map.edge_tag(edge.id).expect("mapped edge");
            match edge.geometry {
                EdgeGeometry::Line { start, end } => source.push_str(&format!(
                    "Line({tag}) = {{{}, {}}};\n",
                    map.vertex_tag(start).expect("mapped start"),
                    map.vertex_tag(end).expect("mapped end")
                )),
                EdgeGeometry::CircularArc { start, center, end } => source.push_str(&format!(
                    "Circle({tag}) = {{{}, {}, {}}};\n",
                    map.vertex_tag(start).expect("mapped start"),
                    map.vertex_tag(center).expect("mapped center"),
                    map.vertex_tag(end).expect("mapped end")
                )),
            }
        }
        write_loop(&mut source, 4000, outer_loop, &map)?;
        for (index, loop_edges) in inner_loops.iter().enumerate() {
            write_loop(&mut source, 4001 + index, loop_edges, &map)?;
        }
        let loops = (0..=inner_loops.len())
            .map(|index| (4000 + index).to_string())
            .collect::<Vec<_>>()
            .join(", ");
        source.push_str(&format!("Plane Surface(3000) = {{{loops}}};\n"));
        for (name, edges) in groups {
            let tags = edges
                .into_iter()
                .map(|edge| {
                    map.edge_tag(edge)
                        .expect("validated mapped edge")
                        .to_string()
                })
                .collect::<Vec<_>>()
                .join(", ");
            source.push_str(&format!("Physical Curve(\"{name}\") = {{{tags}}};\n"));
        }
        source.push_str(&format!(
            "Physical Surface(\"{}\") = {{3000}};\n",
            fluid_name.as_ref()
        ));
        Ok(GeometryGmshExport {
            document: GmshGeoDocument::from_source(MeshDimension::TwoD, source),
            map,
        })
    }

    pub fn rectangular_box(
        geometry: &GeometryTopology,
        body: BodyId,
        boundary_groups: impl IntoIterator<Item = (impl AsRef<str>, Vec<FaceId>)>,
        fluid_name: impl AsRef<str>,
    ) -> Result<GeometryGmshExport, GeometryError> {
        let body_entity = geometry
            .body(body)
            .ok_or_else(|| missing("body", body.get()))?;
        let GeometryBodyRepresentation::Box {
            length,
            width,
            height,
        } = body_entity.representation
        else {
            return Err(GeometryError::InvalidPrimitive {
                message: "Gmsh box export requires a box body".into(),
            });
        };
        validate_name(fluid_name.as_ref())?;
        let mut groups = boundary_groups
            .into_iter()
            .map(|(name, faces)| (name.as_ref().to_owned(), faces))
            .collect::<Vec<_>>();
        groups.sort_by(|left, right| left.0.cmp(&right.0));
        let mut map = GeometryToGmshMap::default();
        map.body_tags.insert(body, 7000);
        for (index, &face) in body_entity.faces.iter().enumerate() {
            map.face_tags.insert(face, index + 1);
        }
        for (name, faces) in &groups {
            validate_name(name)?;
            if faces.is_empty() || faces.iter().any(|face| !map.face_tags.contains_key(face)) {
                return Err(GeometryError::InvalidPrimitive {
                    message: format!("physical group {name:?} references invalid box faces"),
                });
            }
        }
        let mut source = String::from(
            "// Generated by FLURSYS stable geometry exporter.\nSetFactory(\"OpenCASCADE\");\n",
        );
        source.push_str(&format!(
            "Box(7000) = {{0, 0, 0, {length:.17}, {width:.17}, {height:.17}}};\n"
        ));
        for (name, faces) in groups {
            let tags = faces
                .into_iter()
                .map(|face| {
                    map.face_tag(face)
                        .expect("validated mapped face")
                        .to_string()
                })
                .collect::<Vec<_>>()
                .join(", ");
            source.push_str(&format!("Physical Surface(\"{name}\") = {{{tags}}};\n"));
        }
        source.push_str(&format!(
            "Physical Volume(\"{}\") = {{7000}};\n",
            fluid_name.as_ref()
        ));
        Ok(GeometryGmshExport {
            document: GmshGeoDocument::from_source(MeshDimension::ThreeD, source),
            map,
        })
    }
}

fn write_loop(
    source: &mut String,
    tag: usize,
    edges: &[crate::OrientedEdge],
    map: &GeometryToGmshMap,
) -> Result<(), GeometryError> {
    let tags = edges
        .iter()
        .map(|oriented| {
            let tag = map
                .edge_tag(oriented.edge)
                .ok_or_else(|| missing("edge", oriented.edge.get()))?;
            Ok(if oriented.reversed {
                format!("-{tag}")
            } else {
                tag.to_string()
            })
        })
        .collect::<Result<Vec<_>, GeometryError>>()?
        .join(", ");
    source.push_str(&format!("Curve Loop({tag}) = {{{tags}}};\n"));
    Ok(())
}

fn validate_name(name: &str) -> Result<(), GeometryError> {
    if name.is_empty()
        || name
            .chars()
            .any(|character| character == '"' || character.is_control())
    {
        return Err(GeometryError::InvalidPrimitive {
            message: format!("invalid Gmsh physical name {name:?}"),
        });
    }
    Ok(())
}

fn missing(entity: &'static str, id: u64) -> GeometryError {
    GeometryError::EntityNotFound { entity, id }
}
