name: FLURSYS CI

on:
  push:
    tags:
      - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Install Linux GUI dependencies
        run: sudo apt-get update && sudo apt-get install --yes libfontconfig1-dev
      - run: cargo fmt --all -- --check
      - run: cargo check --all-targets --features gui --locked
      - run: cargo test --all-targets --features gui --locked
      - run: cargo clippy --all-targets --features gui --locked -- -D warnings
